17_Testing/starting_code/Museum_App/config/routes.rb
MuseumApp::Application.routes.draw do
  root "paintings#index"
  get 'search', to: 'paintings#search'
  resources :paintings
  resources :museums
  resources :artists
end

17_Testing/starting_code/Museum_App/app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :paintings
	has_many :museums, through: :paintings
  validates :name, presence: true

  def first_name
    name.split.first
  end

end

17_Testing/starting_code/Museum_App/app/models/museum.rb
class Museum < ActiveRecord::Base
	has_many :paintings
	has_many :artists, through: :paintings
end

17_Testing/starting_code/Museum_App/app/models/painting.rb
class Painting < ActiveRecord::Base
  validates :title, :year, :style, presence: true
  validates :year, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  belongs_to :museum
  belongs_to :artist

  def self.search_for(query)
    where('title LIKE :query', :query => "%#{query}%")
  end
end

17_Testing/starting_code/Museum_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

17_Testing/starting_code/Museum_App/app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
	

  def index
  	@museums = Museum.all
  end

  def show
  	@museum = Museum.find(params[:id])
  end

  def new
    @museum = Museum.new
  end

  def create
    @museum = Museum.new(safe_museum_params)
    if @museum.save
      redirect_to @museum
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  private

  def safe_museum_params
    params.require('museum').permit(:name, :city)
  end

end
 

17_Testing/starting_code/Museum_App/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
	  before_action :load_painting, only: [:edit, :show, :update]

  def index
  	@paintings = params[:q] ? Painting.search_for(params[:q]) : Painting.all
  end

  def new
    @painting = Painting.new
  end

  def create
    @painting = Painting.new(safe_painting_params)
    if @painting.save
      redirect_to @painting
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @painting.update(safe_painting_params)
      redirect_to @painting
    else
      render 'edit'
    end
  end

  def show
  end

  private

  def safe_painting_params
    params.require('painting').permit(:title, :year, :style, :image, :museum_id)
  end

  def load_painting
    @painting = Painting.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash.now[:notice] = "Invalid Painting ID #{params[:id]}"
    redirect_to root_path
  end
end

17_Testing/starting_code/Museum_App/app/helpers/application_helper.rb
module ApplicationHelper
end

17_Testing/starting_code/Museum_App/app/helpers/museums_helper.rb
module MuseumsHelper
end

17_Testing/starting_code/Museum_App/app/helpers/paintings_helper.rb
module PaintingsHelper
end

17_Testing/starting_code/Museum_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MuseumApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!-- Styled with love by Salman Ansari :) -->
</head>
<body>
<%= link_to "All Museums", museums_path %>
<%= link_to "All Paintings", paintings_path %>
<div id="container">
  <%= yield %>
</div>

</body>
</html>

17_Testing/starting_code/Museum_App/app/views/museums/_form.html.erb
<% if @museum.errors.any? %>
  <h2>There were errors saving your museum</h2>
  <ul>
    <% @museum.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for @museum do |f| %>
  <fieldset>
    <div class='fields'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class='fields'>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
  </fieldset>
  <%= f.submit %>
<% end %>

<br/>

17_Testing/starting_code/Museum_App/app/views/museums/edit.html.erb
<h1>Edit The Museum</h1>
<%= render 'form' %>

17_Testing/starting_code/Museum_App/app/views/museums/index.html.erb
<h1>Museums</h1>

<h3><%= link_to "+ Add New Museum", new_museum_path %> | <%= link_to "+ Add New Painting", new_painting_path %></h3>

<% @museums.each do |museum| %>
  <hr/>
  <section>
    <h3><%= link_to museum.name, museum %></h3>
    <p><%= museum.city%></p>
  </section>

<% end %>

17_Testing/starting_code/Museum_App/app/views/museums/new.html.erb
<h1>Add a New Museum</h1>
<%= render 'form' %>

17_Testing/starting_code/Museum_App/app/views/museums/show.html.erb
<h1><%= @museum.name %></h1>
<p><%= @museum.city %></p>

<hr/>

<% @museum.paintings.each do |painting| %>
  <section>
    <h3><b>Title</b>: <%= link_to painting.title, painting %></h3>
    <%= image_tag painting.image %>
    <p><b>Year</b>: <%= painting.year%></p>
    <p><b>Style</b>: <%= painting.style%></p>
    <hr/>
  </section>

 <p><%= link_to "Edit Museum", edit_museum_path(@museum) %></p>
 <% end %>